name: AutoRelease

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: tag releases in git
      id: git_tag
      run: |
        CHART_VERSION=$(cat Chart.yaml | grep version | awk '{ print $2 }')
        echo "##[set-output name=version;]${CHART_VERSION}"

        CHART_NAME=$(cat Chart.yaml | grep name | awk '{ print $2 }')
        echo "##[set-output name=name;]${CHART_NAME}"

        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"

        git tag -a "v${CHART_VERSION}" -m "v${CHART_VERSION}" || true
        git push --tags "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

    - uses: actions/checkout@v1
      with:
        repository: evry-ace/helm-charts
        ref: master
        submodules: recursive

    - name: push to evry-ace/helm-charts
      run: |
        cd ../helm-charts; pwd; ls -la

        git fetch origin
        git checkout -b "${CHART_NAME}/v${CHART_VERSION}" origin/master

        # Update submodule
        cd ${CHART_NAME}
        git fetch origin
        git checkout "v${CHART_VERSION}"
        GIT_LOG="$(git log $(git describe --tags HEAD~)..HEAD --oneline | xargs)"

        # Commit and push
        cd ..
        git status
        if [[ `git status --porcelain` ]]; then
          git add ${CHART_NAME}
          git commit \
            -m "${CHART_NAME}: release v${CHART_VERSION}" \
            -m 'Changes since last release:' \
            -m '```' \
            -m "${GIT_LOG}" \
            -m '```'

          git push -u "https://${{ secrets.GITHUB_PAT }}@github.com/evry-ace/helm-charts.git" "${CHART_NAME}/v${CHART_VERSION}"
        fi

      env:
        CHART_VERSION: ${{ steps.git_tag.outputs.version }}
        CHART_NAME: ${{ steps.git_tag.outputs.name }}
